CREATE TABLE IF NOT EXISTS STUDENT(ROLL_NO TEXT PRRIMARY KEY, NAME TEXT NOT NULL, ADDRESS TEXT, PHONE TEXT, AGE INTEGER); 
INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE)VALUES
('1', 'RAM', 'DELHI', '******', 18),
('2', 'RAMESH', 'GURGAON', '******', 18),
('3', 'SUJEET', 'ROHTAK', '******', 20),
('4', 'SURESH', 'DELHI', '******', 18),
('5', 'AMAN', 'ROHTAK', '******', 20),
('6', 'HARSH', 'GURGAON', '******', 18);
--SELECT ALL RRECORDS FRROM THE STUDENT  TABLE TO VERIFY INSERRTION 
SELECT * FROM  STUDENT;
--QUERY  STUDENT WHO  ARE  18 YEARS OLD AND  LIVE IN  DELHI
SELECT *  FROM STUDENT WHERE AGE=18 AND ADDRESS='DELHI';
--QUERRY STUDENT WHO ARE 18  YEARSS OLD AND NAMED RAM
SELECT * FROM STUDENT AGE=18 AND NAME='RAM';
--QUERY STUDENT NAMED RRAM OR SUJEET
SELECT * FROM STUDENT NAME='RAM' OR NAME='SUJEET';
--QUERY STUDENTSS NAMES RRAM ORR AGED 20
SELECT * FROM STUDENT NAME='RAM' OR AGE=20;
--QUERY STUDENTS AGED 18 AND NAMED RAM ORR RAMESH
SELECT * FROM STUDENT AGE=18 AND (NAME='RAM' OR NAME='RAMESH');